// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAf02Y-WQlFrhmolwnYBwo_CSvwBdgZy4',
    appId: '1:13583319652:web:d04a98b54ae15c249dd571',
    messagingSenderId: '13583319652',
    projectId: 'diver-1f985',
    authDomain: 'diver-1f985.firebaseapp.com',
    storageBucket: 'diver-1f985.appspot.com',
    measurementId: 'G-T7YFMGYJ9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX5dph2PnxHETv8M_8xgAMcfklR0mSnqw',
    appId: '1:13583319652:android:06aa8a66aae5f3649dd571',
    messagingSenderId: '13583319652',
    projectId: 'diver-1f985',
    storageBucket: 'diver-1f985.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqJOyJQ0quizEiJJWrkptJal5PLYd4T1E',
    appId: '1:13583319652:ios:5ed5e74b60f734b19dd571',
    messagingSenderId: '13583319652',
    projectId: 'diver-1f985',
    storageBucket: 'diver-1f985.appspot.com',
    iosBundleId: 'com.example.diver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqJOyJQ0quizEiJJWrkptJal5PLYd4T1E',
    appId: '1:13583319652:ios:5ed5e74b60f734b19dd571',
    messagingSenderId: '13583319652',
    projectId: 'diver-1f985',
    storageBucket: 'diver-1f985.appspot.com',
    iosBundleId: 'com.example.diver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAf02Y-WQlFrhmolwnYBwo_CSvwBdgZy4',
    appId: '1:13583319652:web:df1c8ac70e75a6249dd571',
    messagingSenderId: '13583319652',
    projectId: 'diver-1f985',
    authDomain: 'diver-1f985.firebaseapp.com',
    storageBucket: 'diver-1f985.appspot.com',
    measurementId: 'G-G689LDZ3L4',
  );
}
